Repository turtle-friends/chip8, pull requests merged in 2023-02, with the labels that each got.

#27 docs: added README.md file
  README.md
Labels: docs

#29 Added Cpu stub class
  README.md
  inc/Cpu.h
  src/Cpu.cpp
Labels: feature

#31 Implemented the Stack class
  inc/Ram.h
  inc/Stack.h
  src/Ram.cpp
  src/Stack.cpp
Labels: feat
